  server:
    port: 8080
    servlet:
      context-path: /identity

  spring:
    application:
      name: identity-service

    datasource:
      url: jdbc:mysql://localhost:3307/identity_service
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true

      # ===== FEIGN TRACING (CỰC KỲ QUAN TRỌNG) =====
    cloud:
      openfeign:
        micrometer:
          enabled: true   # BẮT BUỘC để propagate trace qua Feign

  jwt:
    secret: 5a17ebf57445277d088804588e896e6ae347ec9815f9f9f0b95065101e022eb8
    expiration-days: 180

  employee:
    service:
      url: http://localhost:8081/employee

  # ================== TRACING (ZIPKIN) ==================
  management:
    tracing:
      enabled: true
      sampling:
        probability: 1.0   # Trace 100% request (MVP đồ án)

    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans
        # ⚠️ dùng localhost vì service chạy ngoài Docker

    endpoints:
      web:
        exposure:
          include: health,info


  logging:
    level:
      io.micrometer.tracing: DEBUG
      org.springframework.cloud.openfeign: DEBUG
      feign: DEBUG