server:
  port: 8082
  servlet:
    context-path: /attendance

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/attendance_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    consumer:
      group-id: attendance-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

employee:
  service:
    url: http://localhost:8081/employee