server:
  port: 8082
  servlet:
    context-path: /attendance

spring:
  application:
    name: attendance-service

  datasource:
    url: jdbc:mysql://localhost:3307/attendance_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cloud:
    openfeign:
      micrometer:
        enabled: true

  kafka:
    consumer:
      group-id: attendance-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

employee:
  service:
    url: http://localhost:8081/employee

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0   # Trace 100% request (demo đồ án)

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      # ⚠️ Dùng localhost vì attendance-service chạy ngoài Docker

  endpoints:
    web:
      exposure:
        include: health,info
