version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
      image: confluentinc/cp-kafka:7.5.0
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
        - "29092:29092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

        KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

  identity-service:
    build:
      context: ./identity-service
    container_name: identity-service
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: identity_service
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  employee-service:
    build:
      context: ./employee-service
    container_name: employee-service
    ports:
      - "8081:8081"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: employee_service
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  attendance-service:
    build:
      context: ./attendance-service
    container_name: attendance-service
    ports:
      - "8082:8082"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: attendance_service
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  request-approval-service:
    build:
      context: ./request-approval-service
    container_name: request-approval-service
    ports:
      - "8083:8083"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: request_approval_service
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  payroll-service:
    build:
      context: ./payroll-service
    container_name: payroll-service
    ports:
      - "8084:8084"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: payroll_service
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
