package com.hrm.common.enums;

public enum ErrorCode {

    // COMMON
    SUCCESS,
    INVALID_REQUEST,
    NOT_FOUND,
    UNAUTHORIZED,
    FORBIDDEN,
    SYSTEM_ERROR,
    USER_ALREADY_EXISTS,
    INVALID_STATE,


    // AUTH
    USERNAME_OR_PASSWORD_INVALID,
    ACCOUNT_LOCKED,

    // BUSINESS
    DATA_ALREADY_EXISTS,
    TIMESHEET_ALREADY_CLOSED
}
